apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.scmType}}-broker-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
  annotations:
    {{- include "snyk-broker.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.brokerType }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.containerPort }}
  selector:
    {{- include "snyk-broker.selectorLabels" . | nindent 4 }}
  loadBalancerSourceRanges:
    {{- with .Values.service.loadBalancerSourceRanges }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
